### PR TITLE
Fix prompts on Windows

### LINKED ISSUE #1163: radio list on Windows contains garbled characters
### Context

running `git town config setup` on Windows

### Problem

1. the cursor in the radio list to select the main branch contains a non-printable character:
  image

2. the checkboxes in the list to select the perennial branches contain non-printable characters:
  image

### PR DESCRIPTION
**Pull request by kevgo**
resolves #1163 

https://github.com/AlecAivazis/survey already supports Windows. The problem with Windows is that by default the Windows terminal cannot print Unicode characters. One can change all sorts of system settings to make it work somehow, but I would prefer that Git Town works out of the box here. 

This PR uses more standardized characters for survey on Windows.

image

image

### CODE REVIEW

**Comment by charlierudolph** [comment]
Looks like you committed a `git-town.exe` file. Can that be removed? And maybe update the gitignore if need be

**Comment by kevgo** [comment]
That was an artifact from debugging my PATH setup on Windows. Removed it. I don't see a need to include it into `.gitignore`, since our Makefile doesn't create it.

File: src/prompt/branch_helpers.go [hunk 1]
```diff
@@ -19,6 +22,9 @@ type askForBranchesOptions struct {
 
 func askForBranch(opts askForBranchOptions) string {
 	result := ""
+	if runtime.GOOS == "windows" {
+		surveyCore.SelectFocusIcon = ">"
+	}
```
Comment (charlierudolph) [inline src/prompt/branch_helpers.go]: Should these updates be moved to some sort of init block? That way, all prompts get these update

**Comment by kevgo** [comment]
Okay, great idea! I have extracted a `prompt.Init` method and call it in the root command. This way it gets activated for all commands, and our prompt interface is [hard to misuse](https://testing.googleblog.com/2018/07/code-health-make-interfaces-hard-to.html).

**Comment by charlierudolph** [comment]
I was thinking of something more like an `init` function like we use in drivers / the commands. It may run those lines more than needed but reduces the need to call it

File: src/prompt/init.go [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+)
+
+// Init configures the prompts to work on Windows
+func Init() {
+	if runtime.GOOS == "windows" {
+		surveyCore.SelectFocusIcon = ">"
+		surveyCore.MarkedOptionIcon = "[x]"
+		surveyCore.UnmarkedOptionIcon = "[ ]"
+	}
+
```
Comment (charlierudolph) [inline src/prompt/init.go]: extra newline that can be removed

Comment (kevgo) [reply src/prompt/init.go]: done

File: src/prompt/init.go [hunk 3]
```diff
@@ -0,0 +1,16 @@
+package prompt
+
+import (
+	"runtime"
+
+	surveyCore "gopkg.in/AlecAivazis/survey.v1/core"
+)
+
+// init configures the prompts to work on Windows
```
Comment (charlierudolph) [inline src/prompt/init.go]: Could be nice to setup appveyor and a have a windows only test for this.
