### PR TITLE
fix git ship bug

### LINKED ISSUE #1060: git ship --abort bug
Given this error message

```
2017/11/29 11:55:32 Cannot deserialize steps: *DriverMergePullRequestStep {"BranchName":"cr-deployConfigType","CommitMessage":"","DefaultCommitMessage":"[refactor 3] move deploy config into own package (#810)"}
```

### PR DESCRIPTION
**Pull request by charlierudolph**
resolves #1060

### CODE REVIEW

File: src/cmd/ship.go [hunk 1]
```diff
@@ -116,6 +116,7 @@ func getShipStepList(config shipConfig) (result steps.StepList) {
 	result.Append(&steps.CheckoutBranchStep{BranchName: branchToMergeInto})
 	canShipWithDriver, defaultCommitMessage := getCanShipWithDriver(config.BranchToShip, branchToMergeInto)
 	if canShipWithDriver {
+		result.Append(&steps.PushBranchStep{BranchName: config.BranchToShip})
```
Comment (charlierudolph) [inline src/cmd/ship.go]: If there are any conflicts, we need to update the remote branch before we merge via the API as otherwise the remote doesn't have the resolutions.
