### PR TITLE
replace characters in temp filename

### LINKED ISSUE #925: Error when running `sync` on Windows
I am running git-town installed manually in a directory on %PATH% on Windows 7.

When I first ran `git-town sync` I got the following error on the Stash Pop step after pulling changes down.

`CONFLICT (content): Merge conflict in src/test.js
2017/05/22 11:29:28 open /tmp/sync_C:_Projects_myProject: The system cannot find the path specified.`

I can resolve the conflict manually - but I'm guessing something when wrong there.

If I've omitted/forgotten any important information let me know so I can update the issue.

A

### PR DESCRIPTION
**Pull request by charlierudolph**
resolves #925 

Not certain how to go about testing this

### CODE REVIEW

File: src/steps/step.go [hunk 1]
```diff
@@ -33,5 +34,10 @@ type SerializedRunState struct {
 }
 
 func getRunResultFilename(command string) string {
-	return fmt.Sprintf("/tmp/%s_%s", command, strings.Replace(git.GetRootDirectory(), "/", "_", -1))
+	replaceCharacterRegexp, err := regexp.Compile("[^A-Za-z0-9]")
```
Comment (kevgo) [inline src/steps/step.go]: We could do '[[:alpha:]]' here.

Comment (charlierudolph) [inline src/steps/step.go]: It would need to be `[[:^alpha:]]`. And you had originally said alpha-numeric which would be `[[:^alnum:]]`. Do you want to stick with alpha numeric?
